name: kuno-market-servant
version: '0.1.0.0'
category: Web, Bitcoin
author: Tebello Thejane
maintainer: tebello@kuno.market
copyright: 2018 Tebello Thejane
license: BSD3
github: kuno-market/kuno-market-servant
extra-source-files:
- README.md
ghc-options:
- -Wall
- -Wtabs
- -Wcompat

dependencies:
- base >=4.7 && <5
- servant-server
- aeson
- time
- deepseq
- text
- scientific

library:
  source-dirs: lib
  exposed-modules:
  - Network.KunoMarket.API.Public
  - Network.KunoMarket.API.Public.Types
  - Network.KunoMarket.API.Global
  - Network.KunoMarket.API.Global.Types

tests:
  public-sample:
    main: public-sample.hs
    source-dirs: test
    dependencies:
      - kuno-market-servant
      - http-client
      - servant-client
    other-modules: []
  public-qc:
    main: public-qc.hs
    source-dirs: test
    dependencies:
      - kuno-market-servant
      - QuickCheck
      - hspec
      - hspec-expectations
      - hspec-contrib
      - random
    other-modules: []
