name: kuno-market-servant
version: '0.1.0.0'
category: Web, Bitcoin
author: Tebello Thejane
maintainer: tebello@kuno.market
copyright: 2018 Tebello Thejane
license: BSD3
github: kuno-market/kuno-market-servant
extra-source-files:
- README.md
ghc-options:
- -Wall
- -Wtabs
- -Wcompat

dependencies:
- base >=4.7 && <5
- servant-server
- aeson
- time
- deepseq
- text
- scientific
- unordered-containers
- vector

library:
  source-dirs: lib
  exposed-modules:
  - Network.KunoMarket.API.Common.Types
  - Network.KunoMarket.API.Public
  - Network.KunoMarket.API.Public.Types
  - Network.KunoMarket.API.Global
  - Network.KunoMarket.API.Global.Types
  - Network.KunoMarket.API.Private
  - Network.KunoMarket.API.Private.Types

tests:
  public-qc:
    main: public-qc.hs
    source-dirs: test
    dependencies:
      - kuno-market-servant
      - QuickCheck
      - hspec
      - hspec-expectations
      - hspec-contrib
      - random
    other-modules: []
  private-qc:
    main: private-qc.hs
    source-dirs: test
    dependencies:
      - kuno-market-servant
      - QuickCheck
      - hspec
      - hspec-expectations
      - hspec-contrib
      - random
      - generic-lens
      - microlens
    other-modules: []
  doctests:
    main: doctests.hs
    source-dirs: test
    dependencies:
      - kuno-market-servant
      - doctest
    other-modules: []
  readme:
    main: readme.lhs
    dependencies:
      - kuno-market-servant
      - markdown-unlit
      - servant-client
      - http-client
    ghc-options:
      - -pgmL markdown-unlit
      - -optL haskell+literate
    other-modules: []
